repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint --disable=all -e W0311 -e C0303 --jobs=0 --indent-string='  ' --recursive=y ./src
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
      - id: tests
        name: tests
        entry: bash -c "PYTHONPATH=src pytest tests/"
        language: system
        always_run: true
        pass_filenames: false
