basic_params:
  years: 5
  channels_impressions: ["Amazon", "TV", "Long-Form Video"]
  channels_clicks: ["Search"]
  frequency_of_campaigns: 1
  start_date: "2017/1/1"
  true_cvr:
  revenue_per_conv:

baseline_params:
  base_p: 100
  trend_p: 2
  temp_var: 8
  temp_coef_mean: 50000
  temp_coef_sd: 5000
  error_std: 90

ad_spend_params:
  campaign_spend_mean: 329000
  campaign_spend_std: 100000
  max_min_proportion_on_each_channel:
    Amazon:
      min: 0.10
      max: 0.35
    TV:
      min: 0.05
      max: 0.30
    Long-Form Video:
      min: 0.01
      max: 0.10
    Search:
      min: 0.10
      max: 0.30

media_params:
  true_cpm:
    Amazon: 3.50
    TV: 1.50
    Long-Form Video: 6.50
  true_cpc:
    Search: 2.60
  noisy_cpm_cpc:
    Amazon:
      loc: 0.0
      scale: 1.0
    TV:
      loc: 0.0
      scale: 1.0
    Long-Form Video:
      loc: 0.0
      scale: 1.0
    Search:
      loc: 0.0
      scale: 1.0

cvr_params:
  Amazon:
    loc: 0.0
    scale: 0.5
  TV:
    loc: 0.0
    scale: 0.5
  Long-Form Video:
    loc: 0.0
    scale: 0.5
  Search:
    loc: 0.0
    scale: 0.5